server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hyuk_blog_db
    username: root
    password: ENC(CzuAGRkXOyiECqlkyIio0w==)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        enable_lazy_load_no_trans: true
        # SQL 로깅 완전 비활성화 (민감한 데이터 노출 방지)
        format_sql: false
        use_sql_comments: false
        # SQL 로깅 비활성화
        show_sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # Thymeleaf를 사용하지 않으므로 관련 설정을 모두 제거했습니다.
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
      cache:
        period: 86400
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
        cache: true

# JWT 설정
jwt:
  secret: hyukBlogJwtSecretKey2024ForDevelopmentOnlyChangeInProduction
  expiration: 86400000  # 24시간 (밀리초) 

# 암호화 설정
encryption:
  enabled: true
  algorithm: AES

# 로깅 설정
logging:
  level:
    com.example.hyuk_blog: INFO
    com.example.hyuk_blog.service.JwtAuthService: DEBUG
    com.example.hyuk_blog.util.JwtUtil: DEBUG
    com.example.hyuk_blog.api.controller.AdminApiController: DEBUG
    org.springframework.security: WARN
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
    # SQL 로깅 비활성화 (민감한 데이터 노출 방지)
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    # JPA 로깅 비활성화
    org.hibernate: WARN
    org.springframework.orm.jpa: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 